/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorklistRouteImport } from './routes/worklist'
import { Route as UsersRouteImport } from './routes/users'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as TestCaseUploadRouteImport } from './routes/test-case-upload'
import { Route as TestCaseApprovalRouteImport } from './routes/test-case-approval'
import { Route as TatLogicRouteImport } from './routes/tat-logic'
import { Route as KpisRouteImport } from './routes/kpis'
import { Route as DefectStatusesRouteImport } from './routes/defect-statuses'
import { Route as CrsRouteImport } from './routes/crs'
import { Route as CrSizesRouteImport } from './routes/cr-sizes'
import { Route as CrAllocationRouteImport } from './routes/cr-allocation'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestCaseReviewCrNumberRouteImport } from './routes/test-case-review.$crNumber'
import { Route as CrsCrNumberRouteImport } from './routes/crs.$crNumber'

const WorklistRoute = WorklistRouteImport.update({
  id: '/worklist',
  path: '/worklist',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TestCaseUploadRoute = TestCaseUploadRouteImport.update({
  id: '/test-case-upload',
  path: '/test-case-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TestCaseApprovalRoute = TestCaseApprovalRouteImport.update({
  id: '/test-case-approval',
  path: '/test-case-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const TatLogicRoute = TatLogicRouteImport.update({
  id: '/tat-logic',
  path: '/tat-logic',
  getParentRoute: () => rootRouteImport,
} as any)
const KpisRoute = KpisRouteImport.update({
  id: '/kpis',
  path: '/kpis',
  getParentRoute: () => rootRouteImport,
} as any)
const DefectStatusesRoute = DefectStatusesRouteImport.update({
  id: '/defect-statuses',
  path: '/defect-statuses',
  getParentRoute: () => rootRouteImport,
} as any)
const CrsRoute = CrsRouteImport.update({
  id: '/crs',
  path: '/crs',
  getParentRoute: () => rootRouteImport,
} as any)
const CrSizesRoute = CrSizesRouteImport.update({
  id: '/cr-sizes',
  path: '/cr-sizes',
  getParentRoute: () => rootRouteImport,
} as any)
const CrAllocationRoute = CrAllocationRouteImport.update({
  id: '/cr-allocation',
  path: '/cr-allocation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestCaseReviewCrNumberRoute = TestCaseReviewCrNumberRouteImport.update({
  id: '/test-case-review/$crNumber',
  path: '/test-case-review/$crNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const CrsCrNumberRoute = CrsCrNumberRouteImport.update({
  id: '/$crNumber',
  path: '/$crNumber',
  getParentRoute: () => CrsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cr-allocation': typeof CrAllocationRoute
  '/cr-sizes': typeof CrSizesRoute
  '/crs': typeof CrsRouteWithChildren
  '/defect-statuses': typeof DefectStatusesRoute
  '/kpis': typeof KpisRoute
  '/tat-logic': typeof TatLogicRoute
  '/test-case-approval': typeof TestCaseApprovalRoute
  '/test-case-upload': typeof TestCaseUploadRoute
  '/upload': typeof UploadRoute
  '/users': typeof UsersRoute
  '/worklist': typeof WorklistRoute
  '/crs/$crNumber': typeof CrsCrNumberRoute
  '/test-case-review/$crNumber': typeof TestCaseReviewCrNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cr-allocation': typeof CrAllocationRoute
  '/cr-sizes': typeof CrSizesRoute
  '/crs': typeof CrsRouteWithChildren
  '/defect-statuses': typeof DefectStatusesRoute
  '/kpis': typeof KpisRoute
  '/tat-logic': typeof TatLogicRoute
  '/test-case-approval': typeof TestCaseApprovalRoute
  '/test-case-upload': typeof TestCaseUploadRoute
  '/upload': typeof UploadRoute
  '/users': typeof UsersRoute
  '/worklist': typeof WorklistRoute
  '/crs/$crNumber': typeof CrsCrNumberRoute
  '/test-case-review/$crNumber': typeof TestCaseReviewCrNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cr-allocation': typeof CrAllocationRoute
  '/cr-sizes': typeof CrSizesRoute
  '/crs': typeof CrsRouteWithChildren
  '/defect-statuses': typeof DefectStatusesRoute
  '/kpis': typeof KpisRoute
  '/tat-logic': typeof TatLogicRoute
  '/test-case-approval': typeof TestCaseApprovalRoute
  '/test-case-upload': typeof TestCaseUploadRoute
  '/upload': typeof UploadRoute
  '/users': typeof UsersRoute
  '/worklist': typeof WorklistRoute
  '/crs/$crNumber': typeof CrsCrNumberRoute
  '/test-case-review/$crNumber': typeof TestCaseReviewCrNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cr-allocation'
    | '/cr-sizes'
    | '/crs'
    | '/defect-statuses'
    | '/kpis'
    | '/tat-logic'
    | '/test-case-approval'
    | '/test-case-upload'
    | '/upload'
    | '/users'
    | '/worklist'
    | '/crs/$crNumber'
    | '/test-case-review/$crNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cr-allocation'
    | '/cr-sizes'
    | '/crs'
    | '/defect-statuses'
    | '/kpis'
    | '/tat-logic'
    | '/test-case-approval'
    | '/test-case-upload'
    | '/upload'
    | '/users'
    | '/worklist'
    | '/crs/$crNumber'
    | '/test-case-review/$crNumber'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/cr-allocation'
    | '/cr-sizes'
    | '/crs'
    | '/defect-statuses'
    | '/kpis'
    | '/tat-logic'
    | '/test-case-approval'
    | '/test-case-upload'
    | '/upload'
    | '/users'
    | '/worklist'
    | '/crs/$crNumber'
    | '/test-case-review/$crNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CrAllocationRoute: typeof CrAllocationRoute
  CrSizesRoute: typeof CrSizesRoute
  CrsRoute: typeof CrsRouteWithChildren
  DefectStatusesRoute: typeof DefectStatusesRoute
  KpisRoute: typeof KpisRoute
  TatLogicRoute: typeof TatLogicRoute
  TestCaseApprovalRoute: typeof TestCaseApprovalRoute
  TestCaseUploadRoute: typeof TestCaseUploadRoute
  UploadRoute: typeof UploadRoute
  UsersRoute: typeof UsersRoute
  WorklistRoute: typeof WorklistRoute
  TestCaseReviewCrNumberRoute: typeof TestCaseReviewCrNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/worklist': {
      id: '/worklist'
      path: '/worklist'
      fullPath: '/worklist'
      preLoaderRoute: typeof WorklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-case-upload': {
      id: '/test-case-upload'
      path: '/test-case-upload'
      fullPath: '/test-case-upload'
      preLoaderRoute: typeof TestCaseUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-case-approval': {
      id: '/test-case-approval'
      path: '/test-case-approval'
      fullPath: '/test-case-approval'
      preLoaderRoute: typeof TestCaseApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tat-logic': {
      id: '/tat-logic'
      path: '/tat-logic'
      fullPath: '/tat-logic'
      preLoaderRoute: typeof TatLogicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kpis': {
      id: '/kpis'
      path: '/kpis'
      fullPath: '/kpis'
      preLoaderRoute: typeof KpisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/defect-statuses': {
      id: '/defect-statuses'
      path: '/defect-statuses'
      fullPath: '/defect-statuses'
      preLoaderRoute: typeof DefectStatusesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crs': {
      id: '/crs'
      path: '/crs'
      fullPath: '/crs'
      preLoaderRoute: typeof CrsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cr-sizes': {
      id: '/cr-sizes'
      path: '/cr-sizes'
      fullPath: '/cr-sizes'
      preLoaderRoute: typeof CrSizesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cr-allocation': {
      id: '/cr-allocation'
      path: '/cr-allocation'
      fullPath: '/cr-allocation'
      preLoaderRoute: typeof CrAllocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-case-review/$crNumber': {
      id: '/test-case-review/$crNumber'
      path: '/test-case-review/$crNumber'
      fullPath: '/test-case-review/$crNumber'
      preLoaderRoute: typeof TestCaseReviewCrNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crs/$crNumber': {
      id: '/crs/$crNumber'
      path: '/$crNumber'
      fullPath: '/crs/$crNumber'
      preLoaderRoute: typeof CrsCrNumberRouteImport
      parentRoute: typeof CrsRoute
    }
  }
}

interface CrsRouteChildren {
  CrsCrNumberRoute: typeof CrsCrNumberRoute
}

const CrsRouteChildren: CrsRouteChildren = {
  CrsCrNumberRoute: CrsCrNumberRoute,
}

const CrsRouteWithChildren = CrsRoute._addFileChildren(CrsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CrAllocationRoute: CrAllocationRoute,
  CrSizesRoute: CrSizesRoute,
  CrsRoute: CrsRouteWithChildren,
  DefectStatusesRoute: DefectStatusesRoute,
  KpisRoute: KpisRoute,
  TatLogicRoute: TatLogicRoute,
  TestCaseApprovalRoute: TestCaseApprovalRoute,
  TestCaseUploadRoute: TestCaseUploadRoute,
  UploadRoute: UploadRoute,
  UsersRoute: UsersRoute,
  WorklistRoute: WorklistRoute,
  TestCaseReviewCrNumberRoute: TestCaseReviewCrNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
